#config_version=6

mode:
  start_events: multiball_jungle_start
  stop_events: multiball_core_stop, multiball_jungle_ended
  priority: 150

multiballs:
  jungle_multiball:
    ball_count: 3
    start_events: multiball_jungle_start
    shoot_again: 8s
    ball_locks: []

variable_player:
  multiball_jungle_start:
    jackpot_lit:
      action: set
      int: 1
    super_jackpot_lit:
      action: set
      int: 0
    jackpot_hits:
      action: set
      int: 0
  multiball_jungle_ended:
    jackpot_lit:
      action: set
      int: 0
    super_jackpot_lit:
      action: set
      int: 0
  jackpot_collected:
    score: 50000
    jackpot_hits: 1
  super_jackpot_collected:
    score: 150000
    super_jackpot_lit:
      action: set
      int: 0

  super_jackpot_lit_event:
    super_jackpot_lit:
      action: set
      int: 1

event_player:
  jackpot_collected:
    - super_jackpot_lit_event{current_player.jackpot_hits >= 2 and current_player.super_jackpot_lit == 0}

light_player:
  multiball_jungle_start:
    l_keep_shooting_playfield: on
  super_jackpot_lit_event:
    l_fivebank_arrow_3: on
