#config_version=6

mode:
  start_events: ball_will_end
  stop_events: bonus_complete
  priority: 90
  code: mpf.modes.bonus.code.bonus.Bonus

mode_settings:
  bonus_entries:
    - entry: bonus_targets
      text: "Targets"
      player_score_entry: bonus_targets
      score: 1000
      reset_player_score_entry: true
    - entry: bonus_loops
      text: "Loops"
      player_score_entry: bonus_loops
      score: 500
      reset_player_score_entry: true
    - entry: bonus_lord_letters
      text: "LORD Letters"
      player_score_entry: bonus_lord_letters
      score: 2500
      reset_player_score_entry: true

slide_player:
  mode_bonus_started: bonus
  bonus_start:
    bonus:
      action: update
      tokens:
        entry: initial
  bonus_entry:
    bonus:
      action: update
