#config_version=6

mode:
  start_events: reset_complete
  stop_events: ball_starting, service_mode_entered
  priority: 10

slide_player:
  mode_attract_started: attract

show_player:
  mode_attract_started:
    attract_wave:
      speed: 1
      loops: -1

hardware_sound_player:
  mode_attract_started:
    "tenacious_the_metal.snd":
      track: 1
      action: play_file
      platform_options:
        loop: true
        no_cache: false
  mode_attract_will_stop:
    stop_track:
      track: 1
      action: stop
