#config_version=6

mode:
  start_events: ball_starting
  stop_events: ball_ended, machine_reset_phase_1
  priority: 200

tilt:
  tilt_warning_switch_tag: tilt_warning
  warnings_to_tilt: 2
  reset_warnings_events: ball_ended
  settle_time: 2s
  multiple_hit_window: 300ms
